### ISSUE TITLE
can't build latest master

### ISSUE THREAD

**Issue by thedevleon** [TobiasBales/PlayuavOSDConfigurator#80]
When trying to build the latest master on Mac OSX El Capitan (running `npm install` before) with `npm run package` I get tons of these:

```
ERROR in ./~/react-toolbox/lib/commons.scss
Module parse failed: /Users/leon/Documents/Development/PixHawk/PlayuavOSDConfigurator/node_modules/react-toolbox/lib/commons.scss Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| @import "./base";
| @import "~normalize.css";
|
 @ ./src/index.js 31:0-41
```

However the application is still created in the dist folder, but when trying to run it, it get:

```

Uncaught Exception:
Error: Cannot find module 'atob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/leon/Documents/Development/PixHawk/PlayuavOSDConfigurator/dist/osx/PlayUAVOSDConfigurator.app/Contents/Resources/app.asar/main.js:5:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/Users/leon/Documents/Development/PixHawk/PlayuavOSDConfigurator/dist/osx/PlayUAVOSDConfigurator.app/Contents/Resources/atom.asar/browser/init.js:158:8)
```

**Comment by StewLG** [comment]
I am closing this issue because it is very old, and I can't repro (although I'm only running on Linux & Windows). 

Thedevleon, if this is still an issue for you, please comment or re-open and I can try to get a Mac build going.
